[build]
builder = "NIXPACKS"

[deploy]
startCommand = "gunicorn app:app --bind 0.0.0.0:$PORT --workers 1"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"

[[services]]
name = "web"
source = "."

[[services]]
name = "worker" 
source = "."
startCommand = "python scripts/send_scheduled_messages.py"