"""Rename type column to template_type in message_templates

Revision ID: 012c7681fe48
Revises: b172ee3534eb
Create Date: 2025-07-20 06:31:39.102906

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '012c7681fe48'
down_revision = 'b172ee3534eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add the new column, but allow it to be nullable for now
    op.add_column('message_templates', sa.Column('template_type', sa.Text(), nullable=True))

    # Step 2: Copy the data from the old 'type' column to the new 'template_type' column
    op.execute('UPDATE message_templates SET template_type = type')

    # Step 3: Now that all rows have data, alter the column to be non-nullable
    op.alter_column('message_templates', 'template_type', nullable=False)

    # Step 4: Drop the old 'type' column
    op.drop_column('message_templates', 'type')
    
    # Other schema changes from autogenerate (if any)
    op.alter_column('message_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('message_templates', 'variables',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('message_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('scheduled_messages', 'delivery_status',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('scheduled_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_scheduled_messages_template_id'), 'scheduled_messages', ['template_id'], unique=False)
    op.create_index(op.f('idx_scheduled_messages_status'), 'scheduled_messages', ['status'], unique=False)
    op.create_index(op.f('idx_scheduled_messages_reservation_id'), 'scheduled_messages', ['reservation_id'], unique=False)
    op.create_index(op.f('idx_scheduled_messages_guest_id'), 'scheduled_messages', ['guest_id'], unique=False)
    op.alter_column('scheduled_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('scheduled_messages', 'delivery_status',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.add_column('message_templates', sa.Column('type', sa.TEXT(), autoincrement=False, nullable=False))
    op.create_index(op.f('idx_message_templates_user_id'), 'message_templates', ['user_id'], unique=False)
    op.create_index(op.f('idx_message_templates_type'), 'message_templates', ['type'], unique=False)
    op.create_index(op.f('idx_message_templates_property_id'), 'message_templates', ['property_id'], unique=False)
    op.alter_column('message_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('message_templates', 'variables',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('message_templates', 'template_type')
    op.create_index(op.f('idx_message_logs_status'), 'message_logs', ['status'], unique=False)
    op.create_index(op.f('idx_message_logs_scheduled_message_id'), 'message_logs', ['scheduled_message_id'], unique=False)
    op.alter_column('message_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_pkc'))
    )
    # ### end Alembic commands ###
