"""add_auto_messaging_to_property_model_fix

Revision ID: 02c87f6ac692
Revises: 65615172ff73
Create Date: 2025-07-21 03:29:24.621307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02c87f6ac692'
down_revision = '65615172ff73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('auto_messaging', sa.Boolean(), server_default=sa.text('true'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'auto_messaging')
    # ### end Alembic commands ###
