"""Add comprehensive KYC verification fields to guests

Revision ID: 54dc17813a9c
Revises: 31286a888c97
Create Date: 2025-09-14 02:59:23.853718

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '54dc17813a9c'
down_revision = '31286a888c97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alembic_version')
    op.add_column('guests', sa.Column('kyc_liveness_score', sa.Float(), nullable=True))
    op.add_column('guests', sa.Column('kyc_face_match_score', sa.Float(), nullable=True))
    op.add_column('guests', sa.Column('kyc_age_estimation', sa.Integer(), nullable=True))
    op.add_column('guests', sa.Column('kyc_gender', sa.Text(), nullable=True))
    op.add_column('guests', sa.Column('kyc_document_expiry', sa.Date(), nullable=True))
    op.add_column('guests', sa.Column('kyc_place_of_birth', sa.Text(), nullable=True))
    op.add_column('guests', sa.Column('kyc_personal_number', sa.Text(), nullable=True))
    op.add_column('guests', sa.Column('kyc_issuing_country', sa.Text(), nullable=True))
    op.add_column('guests', sa.Column('kyc_document_front_image', sa.Text(), nullable=True))
    op.add_column('guests', sa.Column('kyc_document_back_image', sa.Text(), nullable=True))
    op.add_column('guests', sa.Column('kyc_portrait_image', sa.Text(), nullable=True))
    op.add_column('guests', sa.Column('kyc_selfie_image', sa.Text(), nullable=True))
    op.add_column('guests', sa.Column('kyc_ip_location', sa.Text(), nullable=True))
    op.add_column('guests', sa.Column('kyc_verification_warnings', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.drop_index(op.f('idx_message_logs_scheduled_message_id'), table_name='message_logs')
    op.drop_index(op.f('idx_message_logs_status'), table_name='message_logs')
    op.drop_index(op.f('idx_message_templates_property_id'), table_name='message_templates')
    op.drop_index(op.f('idx_message_templates_user_id'), table_name='message_templates')
    op.alter_column('phone_verifications', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('phone_verifications', 'attempts',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('phone_verifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_phone_verifications_expires_at'), table_name='phone_verifications')
    op.drop_index(op.f('ix_phone_verifications_phone_number'), table_name='phone_verifications')
    op.drop_index(op.f('ix_phone_verifications_purpose'), table_name='phone_verifications')
    op.alter_column('properties', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('idx_properties_active'), table_name='properties')
    op.drop_index(op.f('idx_properties_team_id'), table_name='properties')
    op.alter_column('property_team_members', 'role',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('property_team_members', 'invited_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('property_team_members', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('property_team_members', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_property_team_members_active'), table_name='property_team_members')
    op.drop_index(op.f('idx_property_team_members_property_id'), table_name='property_team_members')
    op.drop_index(op.f('idx_property_team_members_user_id'), table_name='property_team_members')
    op.drop_index(op.f('idx_scheduled_messages_guest_id'), table_name='scheduled_messages')
    op.drop_index(op.f('idx_scheduled_messages_reservation_id'), table_name='scheduled_messages')
    op.drop_index(op.f('idx_scheduled_messages_status'), table_name='scheduled_messages')
    op.drop_index(op.f('idx_scheduled_messages_template_id'), table_name='scheduled_messages')
    op.alter_column('team_invitations', 'invited_email',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('team_invitations', 'role',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('team_invitations', 'invitation_token',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('team_invitations', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Text(),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('team_invitations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_team_invitations_email'), table_name='team_invitations')
    op.drop_index(op.f('idx_team_invitations_property_id'), table_name='team_invitations')
    op.drop_index(op.f('idx_team_invitations_status'), table_name='team_invitations')
    op.drop_index(op.f('idx_team_invitations_token'), table_name='team_invitations')
    op.alter_column('team_invitations_new', 'invited_email',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('team_invitations_new', 'invited_phone',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('team_invitations_new', 'invitation_method',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Text(),
               existing_nullable=False,
               existing_server_default=sa.text("'email'::character varying"))
    op.alter_column('team_invitations_new', 'role',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('team_invitations_new', 'invitation_token',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('team_invitations_new', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Text(),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('team_invitations_new', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_team_invitations_new_email'), table_name='team_invitations_new')
    op.drop_index(op.f('idx_team_invitations_new_status'), table_name='team_invitations_new')
    op.drop_index(op.f('idx_team_invitations_new_team_id'), table_name='team_invitations_new')
    op.drop_index(op.f('idx_team_invitations_new_token'), table_name='team_invitations_new')
    op.alter_column('team_members', 'role',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('team_members', 'invited_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('team_members', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('team_members', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_team_members_active'), table_name='team_members')
    op.drop_index(op.f('idx_team_members_role'), table_name='team_members')
    op.drop_index(op.f('idx_team_members_team_id'), table_name='team_members')
    op.drop_index(op.f('idx_team_members_user_id'), table_name='team_members')
    op.alter_column('team_performance', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_team_performance_date'), table_name='team_performance')
    op.drop_index(op.f('idx_team_performance_team_date'), table_name='team_performance')
    op.drop_index(op.f('idx_team_performance_team_id'), table_name='team_performance')
    op.alter_column('teams', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('teams', 'color',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('teams', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('teams', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('teams', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_teams_active'), table_name='teams')
    op.drop_index(op.f('idx_teams_organization_id'), table_name='teams')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_teams_organization_id'), 'teams', ['organization_id'], unique=False)
    op.create_index(op.f('idx_teams_active'), 'teams', ['is_active'], unique=False)
    op.alter_column('teams', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('teams', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('teams', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('teams', 'color',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=7),
               existing_nullable=True)
    op.alter_column('teams', 'name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.create_index(op.f('idx_team_performance_team_id'), 'team_performance', ['team_id'], unique=False)
    op.create_index(op.f('idx_team_performance_team_date'), 'team_performance', ['team_id', 'date'], unique=False)
    op.create_index(op.f('idx_team_performance_date'), 'team_performance', ['date'], unique=False)
    op.alter_column('team_performance', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('idx_team_members_user_id'), 'team_members', ['user_id'], unique=False)
    op.create_index(op.f('idx_team_members_team_id'), 'team_members', ['team_id'], unique=False)
    op.create_index(op.f('idx_team_members_role'), 'team_members', ['role'], unique=False)
    op.create_index(op.f('idx_team_members_active'), 'team_members', ['is_active'], unique=False)
    op.alter_column('team_members', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('team_members', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('team_members', 'invited_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('team_members', 'role',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.create_index(op.f('idx_team_invitations_new_token'), 'team_invitations_new', ['invitation_token'], unique=False)
    op.create_index(op.f('idx_team_invitations_new_team_id'), 'team_invitations_new', ['team_id'], unique=False)
    op.create_index(op.f('idx_team_invitations_new_status'), 'team_invitations_new', ['status'], unique=False)
    op.create_index(op.f('idx_team_invitations_new_email'), 'team_invitations_new', ['invited_email'], unique=False)
    op.alter_column('team_invitations_new', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('team_invitations_new', 'status',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('team_invitations_new', 'invitation_token',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('team_invitations_new', 'role',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('team_invitations_new', 'invitation_method',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False,
               existing_server_default=sa.text("'email'::character varying"))
    op.alter_column('team_invitations_new', 'invited_phone',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('team_invitations_new', 'invited_email',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.create_index(op.f('idx_team_invitations_token'), 'team_invitations', ['invitation_token'], unique=False)
    op.create_index(op.f('idx_team_invitations_status'), 'team_invitations', ['status'], unique=False)
    op.create_index(op.f('idx_team_invitations_property_id'), 'team_invitations', ['property_id'], unique=False)
    op.create_index(op.f('idx_team_invitations_email'), 'team_invitations', ['invited_email'], unique=False)
    op.alter_column('team_invitations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('team_invitations', 'status',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('team_invitations', 'invitation_token',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('team_invitations', 'role',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('team_invitations', 'invited_email',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.create_index(op.f('idx_scheduled_messages_template_id'), 'scheduled_messages', ['template_id'], unique=False)
    op.create_index(op.f('idx_scheduled_messages_status'), 'scheduled_messages', ['status'], unique=False)
    op.create_index(op.f('idx_scheduled_messages_reservation_id'), 'scheduled_messages', ['reservation_id'], unique=False)
    op.create_index(op.f('idx_scheduled_messages_guest_id'), 'scheduled_messages', ['guest_id'], unique=False)
    op.create_index(op.f('idx_property_team_members_user_id'), 'property_team_members', ['user_id'], unique=False)
    op.create_index(op.f('idx_property_team_members_property_id'), 'property_team_members', ['property_id'], unique=False)
    op.create_index(op.f('idx_property_team_members_active'), 'property_team_members', ['is_active'], unique=False)
    op.alter_column('property_team_members', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('property_team_members', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('property_team_members', 'invited_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('property_team_members', 'role',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.create_index(op.f('idx_properties_team_id'), 'properties', ['team_id'], unique=False)
    op.create_index(op.f('idx_properties_active'), 'properties', ['is_active'], unique=False)
    op.alter_column('properties', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.create_index(op.f('ix_phone_verifications_purpose'), 'phone_verifications', ['purpose'], unique=False)
    op.create_index(op.f('ix_phone_verifications_phone_number'), 'phone_verifications', ['phone_number'], unique=False)
    op.create_index(op.f('ix_phone_verifications_expires_at'), 'phone_verifications', ['expires_at'], unique=False)
    op.alter_column('phone_verifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('phone_verifications', 'attempts',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('phone_verifications', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('idx_message_templates_user_id'), 'message_templates', ['user_id'], unique=False)
    op.create_index(op.f('idx_message_templates_property_id'), 'message_templates', ['property_id'], unique=False)
    op.create_index(op.f('idx_message_logs_status'), 'message_logs', ['status'], unique=False)
    op.create_index(op.f('idx_message_logs_scheduled_message_id'), 'message_logs', ['scheduled_message_id'], unique=False)
    op.drop_column('guests', 'kyc_verification_warnings')
    op.drop_column('guests', 'kyc_ip_location')
    op.drop_column('guests', 'kyc_selfie_image')
    op.drop_column('guests', 'kyc_portrait_image')
    op.drop_column('guests', 'kyc_document_back_image')
    op.drop_column('guests', 'kyc_document_front_image')
    op.drop_column('guests', 'kyc_issuing_country')
    op.drop_column('guests', 'kyc_personal_number')
    op.drop_column('guests', 'kyc_place_of_birth')
    op.drop_column('guests', 'kyc_document_expiry')
    op.drop_column('guests', 'kyc_gender')
    op.drop_column('guests', 'kyc_age_estimation')
    op.drop_column('guests', 'kyc_face_match_score')
    op.drop_column('guests', 'kyc_liveness_score')
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_pkc'))
    )
    # ### end Alembic commands ###
