"""Update old verification template types to verification_request

Revision ID: 5fa6d58758ac
Revises: 012c7681fe48
Create Date: 2025-07-20 07:03:18.551424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fa6d58758ac'
down_revision = '012c7681fe48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE message_templates SET template_type = 'verification_request' WHERE template_type = 'verification'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE message_templates SET template_type = 'verification' WHERE template_type = 'verification_request'")
    # ### end Alembic commands ###
