"""Add automation fields to message templates

Revision ID: 65615172ff73
Revises: 5fa6d58758ac
Create Date: 2025-07-20 08:12:11.029879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65615172ff73'
down_revision = '5fa6d58758ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alembic_version')
    op.drop_index(op.f('idx_message_logs_scheduled_message_id'), table_name='message_logs')
    op.drop_index(op.f('idx_message_logs_status'), table_name='message_logs')
    op.add_column('message_templates', sa.Column('trigger_event', sa.Text(), nullable=True))
    op.add_column('message_templates', sa.Column('trigger_offset_value', sa.Integer(), nullable=True))
    op.add_column('message_templates', sa.Column('trigger_offset_unit', sa.Text(), nullable=True))
    op.add_column('message_templates', sa.Column('trigger_direction', sa.Text(), nullable=True))
    op.drop_index(op.f('idx_message_templates_property_id'), table_name='message_templates')
    op.drop_index(op.f('idx_message_templates_user_id'), table_name='message_templates')
    op.drop_index(op.f('idx_scheduled_messages_guest_id'), table_name='scheduled_messages')
    op.drop_index(op.f('idx_scheduled_messages_reservation_id'), table_name='scheduled_messages')
    op.drop_index(op.f('idx_scheduled_messages_status'), table_name='scheduled_messages')
    op.drop_index(op.f('idx_scheduled_messages_template_id'), table_name='scheduled_messages')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_scheduled_messages_template_id'), 'scheduled_messages', ['template_id'], unique=False)
    op.create_index(op.f('idx_scheduled_messages_status'), 'scheduled_messages', ['status'], unique=False)
    op.create_index(op.f('idx_scheduled_messages_reservation_id'), 'scheduled_messages', ['reservation_id'], unique=False)
    op.create_index(op.f('idx_scheduled_messages_guest_id'), 'scheduled_messages', ['guest_id'], unique=False)
    op.create_index(op.f('idx_message_templates_user_id'), 'message_templates', ['user_id'], unique=False)
    op.create_index(op.f('idx_message_templates_property_id'), 'message_templates', ['property_id'], unique=False)
    op.drop_column('message_templates', 'trigger_direction')
    op.drop_column('message_templates', 'trigger_offset_unit')
    op.drop_column('message_templates', 'trigger_offset_value')
    op.drop_column('message_templates', 'trigger_event')
    op.create_index(op.f('idx_message_logs_status'), 'message_logs', ['status'], unique=False)
    op.create_index(op.f('idx_message_logs_scheduled_message_id'), 'message_logs', ['scheduled_message_id'], unique=False)
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_pkc'))
    )
    # ### end Alembic commands ###
