"""Add essential property fields: wifi, times, location, type, access

Revision ID: a982cba7e4ad
Revises: 9845c12be8a1
Create Date: 2025-09-28 14:17:49.822774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a982cba7e4ad'
down_revision = '9845c12be8a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('wifi_name', sa.Text(), nullable=True))
    op.add_column('properties', sa.Column('wifi_password', sa.Text(), nullable=True))
    op.add_column('properties', sa.Column('check_in_time', sa.Time(), nullable=True))
    op.add_column('properties', sa.Column('check_out_time', sa.Time(), nullable=True))
    op.add_column('properties', sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True))
    op.add_column('properties', sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True))
    op.add_column('properties', sa.Column('property_type', sa.String(length=50), nullable=True))
    op.add_column('properties', sa.Column('access_instructions', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'access_instructions')
    op.drop_column('properties', 'property_type')
    op.drop_column('properties', 'longitude')
    op.drop_column('properties', 'latitude')
    op.drop_column('properties', 'check_out_time')
    op.drop_column('properties', 'check_in_time')
    op.drop_column('properties', 'wifi_password')
    op.drop_column('properties', 'wifi_name')
    # ### end Alembic commands ###
