"""Add auto_messaging to Property model

Revision ID: b172ee3534eb
Revises: 7e7abdab41d5
Create Date: 2025-07-13 00:01:20.836233

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b172ee3534eb'
down_revision = '7e7abdab41d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alembic_version')
    op.alter_column('message_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_message_logs_scheduled_message_id'), table_name='message_logs')
    op.drop_index(op.f('idx_message_logs_status'), table_name='message_logs')
    op.alter_column('message_templates', 'variables',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('message_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_message_templates_property_id'), table_name='message_templates')
    op.drop_index(op.f('idx_message_templates_type'), table_name='message_templates')
    op.drop_index(op.f('idx_message_templates_user_id'), table_name='message_templates')
    op.add_column('properties', sa.Column('auto_messaging', sa.Boolean(), server_default=sa.text('true'), nullable=True))
    op.alter_column('scheduled_messages', 'delivery_status',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('scheduled_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_scheduled_messages_guest_id'), table_name='scheduled_messages')
    op.drop_index(op.f('idx_scheduled_messages_reservation_id'), table_name='scheduled_messages')
    op.drop_index(op.f('idx_scheduled_messages_status'), table_name='scheduled_messages')
    op.drop_index(op.f('idx_scheduled_messages_template_id'), table_name='scheduled_messages')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_scheduled_messages_template_id'), 'scheduled_messages', ['template_id'], unique=False)
    op.create_index(op.f('idx_scheduled_messages_status'), 'scheduled_messages', ['status'], unique=False)
    op.create_index(op.f('idx_scheduled_messages_reservation_id'), 'scheduled_messages', ['reservation_id'], unique=False)
    op.create_index(op.f('idx_scheduled_messages_guest_id'), 'scheduled_messages', ['guest_id'], unique=False)
    op.alter_column('scheduled_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('scheduled_messages', 'delivery_status',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('properties', 'auto_messaging')
    op.create_index(op.f('idx_message_templates_user_id'), 'message_templates', ['user_id'], unique=False)
    op.create_index(op.f('idx_message_templates_type'), 'message_templates', ['type'], unique=False)
    op.create_index(op.f('idx_message_templates_property_id'), 'message_templates', ['property_id'], unique=False)
    op.alter_column('message_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('message_templates', 'variables',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_index(op.f('idx_message_logs_status'), 'message_logs', ['status'], unique=False)
    op.create_index(op.f('idx_message_logs_scheduled_message_id'), 'message_logs', ['scheduled_message_id'], unique=False)
    op.alter_column('message_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_pkc'))
    )
    # ### end Alembic commands ###
